/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concesionarioscarlatti;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ds098
 */
public class GUIClientes extends javax.swing.JFrame {

    /**
     * Creates new form GUIClientes
     */
    public GUIClientes(ArrayList<Clientes> clientes) {
        GridLayout gframe = new GridLayout(2,1);
        
        
        
        setLayout(gframe);
        
        JPanel panel = new JPanel();
        GridLayout gl = new GridLayout(clientes.size() + 1, 4);
        panel.setLayout(gl);
        
       
        
        JLabel tnombre = new JLabel("NOMBRE");
        JLabel tape = new JLabel("APELLIDO");
        JLabel tdni = new JLabel("DNI");
        JLabel ttel = new JLabel("TELEFONO");

        panel.add(tnombre);
        panel.add(tape);
        panel.add(tdni);
        panel.add(ttel);

        for (int i = 0; i < clientes.size(); i++) {
            JLabel nombre = new JLabel(clientes.get(i).getNombre());
            JLabel ape = new JLabel(clientes.get(i).getApellido());
            JLabel dni = new JLabel(clientes.get(i).getDni());
            JLabel tel = new JLabel(clientes.get(i).getTelefono() + "");

            panel.add(nombre);
            panel.add(ape);
           panel.add(dni);
            panel.add(tel);

        }
        JButton comprar = new JButton("Comprar");
        JButton cerrar = new JButton("Cerrar");
        
        
        add(panel);
         JPanel panelbotones = new JPanel();
         GridLayout gpanelbotones = new GridLayout(1,2);
        
        panelbotones.setLayout(gpanelbotones);
        add(panelbotones);
        panelbotones.add(comprar);
        panelbotones.add(cerrar);
        
        comprar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 JFrame coches = new JFrame();
                 
                 coches.setVisible(true);
            }
        });
    }

    private GUIClientes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
