/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raices;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ds098
 */
public class NewJFrame extends javax.swing.JFrame {

    ArrayList<Alumno> alumnos = new ArrayList<>();

    JPanel superior, central;
    JButton guardar;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        this.superior = new JPanel();
        this.central = new JPanel();
        setLayout(new BorderLayout());
        add(superior, BorderLayout.NORTH);
        add(central, BorderLayout.CENTER);
        
        guardar = new JButton("Guardar");
        superior.add(guardar);

        RellenarAlumnos();
        GridLayout gframe = new GridLayout(3, 3);
        central.setLayout(gframe);

        for (int i = 0; i < 9; i++) {
            addAlumnos(alumnos.get(i).getNombre(), alumnos.get(i).getApellido());
        }

        setSize(800, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void RellenarAlumnos() {
        Alumno a1 = new Alumno("Jose Luis", "Arranz", false, false, false);
        Alumno a2 = new Alumno("Fabio", "Dimione", false, false, false);
        Alumno a3 = new Alumno("David", "Rehak", false, false, false);
        Alumno a4 = new Alumno("Stefan", "Vladimir", false, false, false);
        Alumno a5 = new Alumno("Noa", "Velasco", false, false, false);
        Alumno a6 = new Alumno("Ainhoa", "Sanjuan", false, false, false);
        Alumno a7 = new Alumno("Andres", "Lamarca", false, false, false);
        Alumno a8 = new Alumno("Carlos", "Navacerrada", false, false, false);
        Alumno a9 = new Alumno("Elena", "Figueroa", false, false, false);

        alumnos.add(a1);
        alumnos.add(a2);
        alumnos.add(a3);
        alumnos.add(a4);
        alumnos.add(a5);
        alumnos.add(a6);
        alumnos.add(a7);
        alumnos.add(a8);
        alumnos.add(a9);

    }
    
    public void guardaAlumnos(){
        // @TODO: meter un try con resources para escribir
    }

    public void addAlumnos(String nombre, String apellido) {

        JPanel alumno = new JPanel();

        GridLayout gr = new GridLayout(2, 1);
        alumno.setLayout(gr);

        JPanel checks = new JPanel();

        GridLayout grchecks = new GridLayout(1, 3);
        checks.setLayout(grchecks);

        JLabel al = new JLabel(nombre + ", " + apellido);

        ButtonGroup cbg = new ButtonGroup();

        JCheckBox just = new JCheckBox("J");

        JCheckBox injust = new JCheckBox("I");
        JCheckBox retraso = new JCheckBox("R");
        cbg.add(just);
        cbg.add(injust);
        cbg.add(retraso);

        checks.add(just);
        checks.add(injust);
        checks.add(retraso);

        alumno.add(al);
        alumno.add(checks);

        central.add(alumno);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
