
package testeo;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;

public class TorneoBrujos extends javax.swing.JFrame {

    /**
     * Creates new form TorneoBrujos
     */
    public TorneoBrujos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Brujo3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        brujo1 = new javax.swing.JPanel();
        jLabelBrujo1 = new javax.swing.JLabel();
        Brujo2 = new javax.swing.JPanel();
        jLabelBrujo2 = new javax.swing.JLabel();
        jButtonBrujo1 = new javax.swing.JButton();
        jButtonBrujo2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        brujo3 = new javax.swing.JPanel();
        jLabelBrujo3 = new javax.swing.JLabel();
        Brujo4 = new javax.swing.JPanel();
        jLabelBrujo4 = new javax.swing.JLabel();
        jButtonBrujo3 = new javax.swing.JButton();
        jButtonBrujo4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonFinale = new javax.swing.JButton();

        Brujo3.setBackground(new java.awt.Color(30, 130, 30));

        javax.swing.GroupLayout Brujo3Layout = new javax.swing.GroupLayout(Brujo3);
        Brujo3.setLayout(Brujo3Layout);
        Brujo3Layout.setHorizontalGroup(
            Brujo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        Brujo3Layout.setVerticalGroup(
            Brujo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 130));

        brujo1.setBackground(new java.awt.Color(30, 130, 30));

        jLabelBrujo1.setText("jLabel1");

        javax.swing.GroupLayout brujo1Layout = new javax.swing.GroupLayout(brujo1);
        brujo1.setLayout(brujo1Layout);
        brujo1Layout.setHorizontalGroup(
            brujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brujo1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabelBrujo1)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        brujo1Layout.setVerticalGroup(
            brujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brujo1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabelBrujo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Brujo2.setBackground(new java.awt.Color(30, 130, 30));

        jLabelBrujo2.setText("jLabel1");

        javax.swing.GroupLayout Brujo2Layout = new javax.swing.GroupLayout(Brujo2);
        Brujo2.setLayout(Brujo2Layout);
        Brujo2Layout.setHorizontalGroup(
            Brujo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Brujo2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabelBrujo2)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Brujo2Layout.setVerticalGroup(
            Brujo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Brujo2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabelBrujo2)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jButtonBrujo1.setText("GANA");
        jButtonBrujo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrujo1ActionPerformed(evt);
            }
        });

        jButtonBrujo2.setText("GANA");
        jButtonBrujo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrujo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(brujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonBrujo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jButtonBrujo2)
                .addGap(30, 30, 30)
                .addComponent(Brujo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(brujo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Brujo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBrujo1)
                    .addComponent(jButtonBrujo2))
                .addGap(95, 95, 95))
        );

        jPanel2.setBackground(new java.awt.Color(130, 30, 30));

        brujo3.setBackground(new java.awt.Color(30, 130, 30));

        jLabelBrujo3.setText("jLabel1");

        javax.swing.GroupLayout brujo3Layout = new javax.swing.GroupLayout(brujo3);
        brujo3.setLayout(brujo3Layout);
        brujo3Layout.setHorizontalGroup(
            brujo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brujo3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabelBrujo3)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        brujo3Layout.setVerticalGroup(
            brujo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brujo3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabelBrujo3)
                .addGap(71, 71, 71))
        );

        Brujo4.setBackground(new java.awt.Color(30, 130, 30));

        jLabelBrujo4.setText("jLabel1");

        javax.swing.GroupLayout Brujo4Layout = new javax.swing.GroupLayout(Brujo4);
        Brujo4.setLayout(Brujo4Layout);
        Brujo4Layout.setHorizontalGroup(
            Brujo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Brujo4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabelBrujo4)
                .addGap(71, 71, 71))
        );
        Brujo4Layout.setVerticalGroup(
            Brujo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Brujo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBrujo4)
                .addGap(70, 70, 70))
        );

        jButtonBrujo3.setText("GANA");
        jButtonBrujo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrujo3ActionPerformed(evt);
            }
        });

        jButtonBrujo4.setText("GANA");
        jButtonBrujo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrujo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(brujo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonBrujo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBrujo4)
                .addGap(31, 31, 31)
                .addComponent(Brujo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Brujo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brujo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBrujo3)
                    .addComponent(jButtonBrujo4))
                .addGap(95, 95, 95))
        );

        jPanel3.setBackground(new java.awt.Color(130, 130, 130));

        jButtonFinale.setText("LA FINAL");
        jButtonFinale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButtonFinale, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFinale, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrujo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrujo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrujo1ActionPerformed

    private void jButtonBrujo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrujo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrujo2ActionPerformed

    private void jButtonBrujo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrujo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrujo3ActionPerformed

    private void jButtonBrujo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrujo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrujo4ActionPerformed

    private void jButtonFinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TorneoBrujos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TorneoBrujos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TorneoBrujos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TorneoBrujos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TorneoBrujos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Brujo2;
    private javax.swing.JPanel Brujo3;
    private javax.swing.JPanel Brujo4;
    private javax.swing.JPanel brujo1;
    private javax.swing.JPanel brujo3;
    private javax.swing.JButton jButtonBrujo1;
    private javax.swing.JButton jButtonBrujo2;
    private javax.swing.JButton jButtonBrujo3;
    private javax.swing.JButton jButtonBrujo4;
    private javax.swing.JButton jButtonFinale;
    private javax.swing.JLabel jLabelBrujo1;
    private javax.swing.JLabel jLabelBrujo2;
    private javax.swing.JLabel jLabelBrujo3;
    private javax.swing.JLabel jLabelBrujo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
